name: Build and Test Feature Branch
on:
    push:
        branches-ignore:
            - main

jobs:
    build-and-test:
        uses: ./.github/workflows/reusable-setup-build-test.yaml
        with:
            build_command: npm run build
        secrets:
            SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
