name: 'Reusable: Deploy to Cloudflare Workers'
on:
    workflow_call:
        secrets:
            CLOUDFLARE_API_TOKEN:
                required: true
            CLOUDFLARE_ACCOUNT_ID:
                required: true

jobs:
    deploy-worker:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version-file: '.nvmrc'
                  cache: 'npm'

            - name: Cache node_modules
              uses: actions/cache@v4
              id: node-modules-cache
              with:
                  path: '**/node_modules'
                  key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

            - name: Install Dependencies
              if: steps.node-modules-cache.outputs.cache-hit != 'true'
              run: npm ci

            # Restore the API public directory cache from the build job
            - name: Restore API public directory
              id: restore-api-public
              uses: actions/cache@v4
              with:
                  path: apps/api/public
                  key: ${{ runner.os }}-api-public-${{ github.sha }}
                  fail-on-cache-miss: true

            # Restore the shared dist directory cache from the build job
            - name: Restore shared build directory
              id: restore-shared-dist
              uses: actions/cache@v4
              with:
                  path: packages/shared/dist
                  key: ${{ runner.os }}-shared-dist-${{ github.sha }}
                  fail-on-cache-miss: true

            # Restore the API handlers dist directory cache from the build job
            - name: Restore API handlers build directory
              id: restore-api-handlers-dist
              uses: actions/cache@v4
              with:
                  path: packages/api-handlers/dist
                  key: ${{ runner.os }}-api-handlers-dist-${{ github.sha }}
                  fail-on-cache-miss: true

            - name: Run Tests
              run: npm run test:ci

            - name: Build & Deploy Worker
              uses: cloudflare/wrangler-action@v3
              with:
                  apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                  workingDirectory: 'apps/api'
